### ISSUE TITLE
6.0.0 broken - Could not find an appender named [ASYNC_CONSOLE]

### ISSUE THREAD

**Issue by timja** [hmcts/java-logging#350]
```
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [ASYNC_CONSOLE]. Did you define it below instead of above in the configuration file?
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:179)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:232)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	... 103 more
```

**Comment by amstevenson** [comment]
https://github.com/hmcts/spring-boot-template/pull/352
